# Generated by Django 5.1.6 on 2025-03-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgt_url', models.CharField(max_length=500, verbose_name='Ссылка для проверки')),
            ],
        ),
    ]
