# Generated by Django 5.1.6 on 2025-03-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200, verbose_name='Домен для мониторинга')),
                ('project_id', models.CharField(max_length=200, verbose_name='ID проекта в топвизор')),
                ('region_index', models.CharField(max_length=200, verbose_name='Индекс региона')),
                ('group_id', models.CharField(max_length=200, verbose_name='ID группы ключей')),
            ],
        ),
    ]
