# Generated by Django 5.1.6 on 2025-03-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topvisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringgroup',
            name='filterbygroup',
            field=models.BooleanField(default=False, verbose_name='Мониторинг без группы'),
        ),
    ]
