# Generated by Django 5.1.6 on 2025-03-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topvisor', '0003_monitoringgroupresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringgroup',
            name='name_Group',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название группы'),
        ),
        migrations.AddField(
            model_name='monitoringgroup',
            name='name_vertical',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название вертикали'),
        ),
        migrations.AlterField(
            model_name='monitoringgroupresult',
            name='top101_1000',
            field=models.CharField(blank=True, max_length=200, verbose_name='В ТОП101-10000'),
        ),
    ]
