# Generated by Django 5.1.6 on 2025-03-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topvisor', '0004_monitoringgroup_name_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringgroup',
            name='searchengine',
            field=models.CharField(blank=True, max_length=200, verbose_name='Поисковая система'),
        ),
    ]
