# Generated by Django 5.1.6 on 2025-03-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topvisor', '0005_monitoringgroup_searchengine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringgroup',
            name='name_Group',
            field=models.CharField(max_length=200, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='monitoringgroup',
            name='name_vertical',
            field=models.CharField(max_length=200, verbose_name='Название вертикали'),
        ),
        migrations.AlterField(
            model_name='monitoringgroup',
            name='searchengine',
            field=models.CharField(max_length=200, verbose_name='Поисковая система'),
        ),
    ]
