# Generated by Django 5.1.6 on 2025-03-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topvisor', '0007_alter_monitoringgroupresult_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringgroup',
            name='name_product',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название Продукта'),
        ),
    ]
